services:
  frontend:
    image: ghcr.io/orkwitzel/chatroom-frontend:latest
    container_name: cios-frontend
    restart: unless-stopped
    ports:
      - 3000:80

  backend:
    image: ghcr.io/orkwitzel/chatroom-backend:latest
    container_name: cios-backend
    restart: unless-stopped
    ports:
      - 4000:80