FROM oven/bun:latest AS build
ARG BACKEND_URL=ws://localhost:4000
WORKDIR /app
COPY . .
RUN bun i --frozen-lockfile
WORKDIR /app/packages/frontend
ENV VITE_BACKEND_URL=${BACKEND_URL}
RUN bun run build

FROM nginx:1.29.1-alpine-slim AS base
COPY --from=build /app/packages/frontend/dist /usr/share/nginx/html
COPY nginx/frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80